# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.storage_controller import StorageController  # noqa: E501
from pylivoltek.rest import ApiException


class TestStorageController(unittest.TestCase):
    """StorageController unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageController(self):
        """Test StorageController"""
        # Construct model with required fields
        sn = "SN123456789"
        model_type = "LV-5000"

        model = StorageController(sn=sn, model_type=model_type)

        # Assert instance type
        self.assertIsInstance(model, StorageController)

        # Assert fields are preserved
        self.assertEqual(model.sn, sn)
        self.assertEqual(model.model_type, model_type)

        # Test basic behavior - serialization
        model_dict = model.to_dict()
        self.assertEqual(model_dict['sn'], sn)
        self.assertEqual(model_dict['model_type'], model_type)

        # Test equality
        model2 = StorageController(sn=sn, model_type=model_type)
        self.assertEqual(model, model2)


if __name__ == '__main__':
    unittest.main()