# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.grid_energy_history_record import GridEnergyHistoryRecord  # noqa: E501
from pylivoltek.rest import ApiException


class TestGridEnergyHistoryRecord(unittest.TestCase):
    """GridEnergyHistoryRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGridEnergyHistoryRecord(self):
        """Test GridEnergyHistoryRecord"""
        # Construct object with representative values
        site_id = "SITE_001"
        ts = 1678901234
        positive = 150.25
        negative = 75.50

        model = GridEnergyHistoryRecord(
            site_id=site_id,
            ts=ts,
            positive=positive,
            negative=negative
        )

        # Assert instance type
        self.assertIsInstance(model, GridEnergyHistoryRecord)

        # Assert each attribute equals the provided value
        self.assertEqual(model.site_id, site_id)
        self.assertEqual(model.ts, ts)
        self.assertEqual(model.positive, positive)
        self.assertEqual(model.negative, negative)

        # Test serialization round-trip (to_dict)
        model_dict = model.to_dict()
        self.assertEqual(model_dict['site_id'], site_id)
        self.assertEqual(model_dict['ts'], ts)
        self.assertEqual(model_dict['positive'], positive)
        self.assertEqual(model_dict['negative'], negative)


if __name__ == '__main__':
    unittest.main()