# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.site_energy_reading import SiteEnergyReading  # noqa: E501
from pylivoltek.rest import ApiException


class TestSiteEnergyReading(unittest.TestCase):
    """SiteEnergyReading unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteEnergyReading(self):
        """Test SiteEnergyReading"""
        # Instantiate with example values
        site_id = "SITE_12345"
        ts = 1678901234
        positive = 250.75
        negative = 125.50

        model = SiteEnergyReading(
            site_id=site_id,
            ts=ts,
            positive=positive,
            negative=negative
        )

        # Assert instance type
        self.assertIsInstance(model, SiteEnergyReading)

        # Assert fields match inputs
        self.assertEqual(model.site_id, site_id)
        self.assertEqual(model.ts, ts)
        self.assertEqual(model.positive, positive)
        self.assertEqual(model.negative, negative)

        # Test serialization/deserialization
        model_dict = model.to_dict()
        self.assertEqual(model_dict['site_id'], site_id)
        self.assertEqual(model_dict['ts'], ts)
        self.assertEqual(model_dict['positive'], positive)
        self.assertEqual(model_dict['negative'], negative)

        # Test string representation
        model_str = model.to_str()
        self.assertIsNotNone(model_str)


if __name__ == '__main__':
    unittest.main()