# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.energy_measurement import EnergyMeasurement  # noqa: E501
from pylivoltek.rest import ApiException


class TestEnergyMeasurement(unittest.TestCase):
    """EnergyMeasurement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnergyMeasurement(self):
        """Test EnergyMeasurement"""
        # Construct object with realistic example values
        value = 1250.75
        unit = "kWh"

        model = EnergyMeasurement(value=value, unit=unit)

        # Assert instance type
        self.assertIsInstance(model, EnergyMeasurement)

        # Assert attributes equal provided values
        self.assertEqual(model.value, value)
        self.assertEqual(model.unit, unit)

        # Validate dict/JSON serialization
        model_dict = model.to_dict()
        self.assertEqual(model_dict['value'], value)
        self.assertEqual(model_dict['unit'], unit)

        # Test string representation
        model_str = model.to_str()
        self.assertIn(str(value), model_str)
        self.assertIn(unit, model_str)


if __name__ == '__main__':
    unittest.main()