# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.energy_history_point import EnergyHistoryPoint  # noqa: E501
from pylivoltek.rest import ApiException


class TestEnergyHistoryPoint(unittest.TestCase):
    """EnergyHistoryPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnergyHistoryPoint(self):
        """Test EnergyHistoryPoint"""
        # Construct object with example values
        ts = 1678901234
        value = 123.45

        model = EnergyHistoryPoint(ts=ts, value=value)

        # Assert instance type
        self.assertIsInstance(model, EnergyHistoryPoint)

        # Assert attributes match provided values
        self.assertEqual(model.ts, ts)
        self.assertEqual(model.value, value)

        # Test serialization round-trip
        model_dict = model.to_dict()
        self.assertEqual(model_dict['ts'], ts)
        self.assertEqual(model_dict['value'], value)

        # Verify to_str works
        model_str = model.to_str()
        self.assertIsNotNone(model_str)


if __name__ == '__main__':
    unittest.main()