# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.device_api_response import DeviceApiResponse  # noqa: E501
from pylivoltek.rest import ApiException


class TestDeviceApiResponse(unittest.TestCase):
    """DeviceApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceApiResponse(self):
        """Test DeviceApiResponse"""
        # Construct object with example values
        code = 200
        message = "Success"
        data = {"device_id": "12345", "status": "active"}

        model = DeviceApiResponse(code=code, message=message, data=data)

        # Assert instance type
        self.assertIsInstance(model, DeviceApiResponse)

        # Assert attributes match provided values
        self.assertEqual(model.code, code)
        self.assertEqual(model.message, message)
        self.assertEqual(model.data, data)

        # Test serialization
        model_dict = model.to_dict()
        self.assertEqual(model_dict['code'], code)
        self.assertEqual(model_dict['message'], message)
        self.assertEqual(model_dict['data'], data)


if __name__ == '__main__':
    unittest.main()