# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.utility_energy_totals import UtilityEnergyTotals  # noqa: E501
from pylivoltek.rest import ApiException


class TestUtilityEnergyTotals(unittest.TestCase):
    """UtilityEnergyTotals unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUtilityEnergyTotals(self):
        """Test UtilityEnergyTotals"""
        # Import EnergyMeasurement for etotal_to_grid field
        from pylivoltek.models.energy_measurement import EnergyMeasurement

        # Construct instance with required attributes
        site_id = "SITE_001"
        etotal_to_grid = EnergyMeasurement(value=500.75, unit="kWh")
        etotal_from_grid = {"value": 300.50, "unit": "kWh"}

        model = UtilityEnergyTotals(
            site_id=site_id,
            etotal_to_grid=etotal_to_grid,
            etotal_from_grid=etotal_from_grid
        )

        # Assert instance type
        self.assertIsInstance(model, UtilityEnergyTotals)

        # Assert instance attributes equal the inputs
        self.assertEqual(model.site_id, site_id)
        self.assertIsInstance(model.etotal_to_grid, EnergyMeasurement)
        self.assertEqual(model.etotal_to_grid.value, 500.75)
        self.assertEqual(model.etotal_from_grid, etotal_from_grid)

        # Test serialization/deserialization preserves values
        model_dict = model.to_dict()
        self.assertEqual(model_dict['site_id'], site_id)
        self.assertIsInstance(model_dict['etotal_to_grid'], dict)
        self.assertEqual(model_dict['etotal_to_grid']['value'], 500.75)
        self.assertEqual(model_dict['etotal_from_grid'], etotal_from_grid)


if __name__ == '__main__':
    unittest.main()