# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.recent_solar_energy_response import RecentSolarEnergyResponse  # noqa: E501
from pylivoltek.rest import ApiException


class TestRecentSolarEnergyResponse(unittest.TestCase):
    """RecentSolarEnergyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecentSolarEnergyResponse(self):
        """Test RecentSolarEnergyResponse"""
        # Import SiteEnergyReading for data field
        from pylivoltek.models.site_energy_reading import SiteEnergyReading

        # Construct object with example values
        code = 200
        message = "Success"
        data = SiteEnergyReading(
            site_id="SITE_001",
            ts=1678901234,
            positive=100.5,
            negative=50.25
        )

        model = RecentSolarEnergyResponse(code=code, message=message, data=data)

        # Assert instance type
        self.assertIsInstance(model, RecentSolarEnergyResponse)

        # Assert each attribute
        self.assertEqual(model.code, code)
        self.assertEqual(model.message, message)
        self.assertIsInstance(model.data, SiteEnergyReading)
        self.assertEqual(model.data.site_id, "SITE_001")

        # Test serialization/deserialization
        model_dict = model.to_dict()
        self.assertEqual(model_dict['code'], code)
        self.assertEqual(model_dict['message'], message)
        self.assertIsInstance(model_dict['data'], dict)
        self.assertEqual(model_dict['data']['site_id'], "SITE_001")


if __name__ == '__main__':
    unittest.main()