# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class BessRemoteStartStopRequest(object):
    """Request body for remote BESS start/stop commands."""

    swagger_types = {
        'account': 'object',
        'pwd': 'object',
        'sn': 'object',
        'control_type': 'int'
    }

    attribute_map = {
        'account': 'account',
        'pwd': 'pwd',
        'sn': 'sn',
        'control_type': 'controlType'
    }

    def __init__(self, account=None, pwd=None, sn=None, control_type=None):  # noqa: E501
        self._account = None
        self._pwd = None
        self._sn = None
        self._control_type = None
        self.discriminator = None
        if account is not None:
            self.account = account
        if pwd is not None:
            self.pwd = pwd
        if sn is not None:
            self.sn = sn
        if control_type is not None:
            self.control_type = control_type

    @property
    def account(self):
        return self._account

    @account.setter
    def account(self, account):
        self._account = account

    @property
    def pwd(self):
        return self._pwd

    @pwd.setter
    def pwd(self, pwd):
        self._pwd = pwd

    @property
    def sn(self):
        return self._sn

    @sn.setter
    def sn(self, sn):
        self._sn = sn

    @property
    def control_type(self):
        return self._control_type

    @control_type.setter
    def control_type(self, control_type):
        self._control_type = control_type

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BessRemoteStartStopRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, BessRemoteStartStopRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
