# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class BessWorkModeScheduleEntry(object):
    """User-defined work-mode schedule entry for a BESS device."""

    swagger_types = {
        'start_hour': 'int',
        'start_min': 'int',
        'end_hour': 'int',
        'end_min': 'int',
        'charge_type': 'int',
        'charging_days': 'list[int]'
    }

    attribute_map = {
        'start_hour': 'startHour',
        'start_min': 'startMin',
        'end_hour': 'endHour',
        'end_min': 'endMin',
        'charge_type': 'chargeType',
        'charging_days': 'chargingDays'
    }

    def __init__(self, start_hour=None, start_min=None, end_hour=None, end_min=None, charge_type=None, charging_days=None):  # noqa: E501
        self._start_hour = None
        self._start_min = None
        self._end_hour = None
        self._end_min = None
        self._charge_type = None
        self._charging_days = None
        self.discriminator = None
        if start_hour is not None:
            self.start_hour = start_hour
        if start_min is not None:
            self.start_min = start_min
        if end_hour is not None:
            self.end_hour = end_hour
        if end_min is not None:
            self.end_min = end_min
        if charge_type is not None:
            self.charge_type = charge_type
        if charging_days is not None:
            self.charging_days = charging_days

    @property
    def start_hour(self):
        return self._start_hour

    @start_hour.setter
    def start_hour(self, start_hour):
        self._start_hour = start_hour

    @property
    def start_min(self):
        return self._start_min

    @start_min.setter
    def start_min(self, start_min):
        self._start_min = start_min

    @property
    def end_hour(self):
        return self._end_hour

    @end_hour.setter
    def end_hour(self, end_hour):
        self._end_hour = end_hour

    @property
    def end_min(self):
        return self._end_min

    @end_min.setter
    def end_min(self, end_min):
        self._end_min = end_min

    @property
    def charge_type(self):
        return self._charge_type

    @charge_type.setter
    def charge_type(self, charge_type):
        self._charge_type = charge_type

    @property
    def charging_days(self):
        return self._charging_days

    @charging_days.setter
    def charging_days(self, charging_days):
        self._charging_days = charging_days

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BessWorkModeScheduleEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, BessWorkModeScheduleEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
