# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class BessDeviceDescriptionResponse(object):
    """Envelope for device-description responses with tolerant flat-field support."""

    swagger_types = {
        'code': 'object',
        'message': 'object',
        'data': 'BessDeviceDescription',
        'product_type': 'object',
        'protocol_version': 'object',
        'supported_command': 'object',
        'work_mode': 'object'
    }

    attribute_map = {
        'code': 'code',
        'message': 'message',
        'data': 'data',
        'product_type': 'productType',
        'protocol_version': 'protocolVersion',
        'supported_command': 'supportedCommand',
        'work_mode': 'workMode'
    }

    def __init__(self, code=None, message=None, data=None, product_type=None, protocol_version=None, supported_command=None, work_mode=None):  # noqa: E501
        self._code = None
        self._message = None
        self._data = None
        self._product_type = None
        self._protocol_version = None
        self._supported_command = None
        self._work_mode = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if message is not None:
            self.message = message
        if data is not None:
            self.data = data
        if product_type is not None:
            self.product_type = product_type
        if protocol_version is not None:
            self.protocol_version = protocol_version
        if supported_command is not None:
            self.supported_command = supported_command
        if work_mode is not None:
            self.work_mode = work_mode

    @property
    def code(self):
        return self._code

    @code.setter
    def code(self, code):
        self._code = code

    @property
    def message(self):
        return self._message

    @message.setter
    def message(self, message):
        self._message = message

    @property
    def data(self):
        return self._data

    @data.setter
    def data(self, data):
        self._data = data

    @property
    def product_type(self):
        return self._product_type

    @product_type.setter
    def product_type(self, product_type):
        self._product_type = product_type

    @property
    def protocol_version(self):
        return self._protocol_version

    @protocol_version.setter
    def protocol_version(self, protocol_version):
        self._protocol_version = protocol_version

    @property
    def supported_command(self):
        return self._supported_command

    @supported_command.setter
    def supported_command(self, supported_command):
        self._supported_command = supported_command

    @property
    def work_mode(self):
        return self._work_mode

    @work_mode.setter
    def work_mode(self, work_mode):
        self._work_mode = work_mode

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BessDeviceDescriptionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, BessDeviceDescriptionResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
