# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class BessWorkModeSetRequest(object):
    """Request body for updating a BESS device work mode and schedule."""

    swagger_types = {
        'account': 'object',
        'pwd': 'object',
        'sn': 'object',
        'work_mode': 'int',
        'schedule_list': 'list[BessWorkModeScheduleEntry]'
    }

    attribute_map = {
        'account': 'account',
        'pwd': 'pwd',
        'sn': 'sn',
        'work_mode': 'workMode',
        'schedule_list': 'scheduleList'
    }

    def __init__(self, account=None, pwd=None, sn=None, work_mode=None, schedule_list=None):  # noqa: E501
        self._account = None
        self._pwd = None
        self._sn = None
        self._work_mode = None
        self._schedule_list = None
        self.discriminator = None
        if account is not None:
            self.account = account
        if pwd is not None:
            self.pwd = pwd
        if sn is not None:
            self.sn = sn
        if work_mode is not None:
            self.work_mode = work_mode
        if schedule_list is not None:
            self.schedule_list = schedule_list

    @property
    def account(self):
        return self._account

    @account.setter
    def account(self, account):
        self._account = account

    @property
    def pwd(self):
        return self._pwd

    @pwd.setter
    def pwd(self, pwd):
        self._pwd = pwd

    @property
    def sn(self):
        return self._sn

    @sn.setter
    def sn(self, sn):
        self._sn = sn

    @property
    def work_mode(self):
        return self._work_mode

    @work_mode.setter
    def work_mode(self, work_mode):
        self._work_mode = work_mode

    @property
    def schedule_list(self):
        return self._schedule_list

    @schedule_list.setter
    def schedule_list(self, schedule_list):
        self._schedule_list = schedule_list

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BessWorkModeSetRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, BessWorkModeSetRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
