# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ChargingStation(object):
    """Charging-station record returned by the query endpoint."""

    swagger_types = {
        'adress': 'object',
        'agent': 'object',
        'agent_and_parent': 'list[object]',
        'battery_capacity': 'object',
        'battery_capacity_unit': 'object',
        'charging_capacity': 'object',
        'charging_type': 'object',
        'charging_type_name': 'object',
        'code_name': 'object',
        'country': 'object',
        'country_name': 'object',
        'country_value': 'object',
        'create_source': 'object',
        'creator_id': 'object',
        'creator_type': 'object',
        'currency_symbol': 'object',
        'currency_unit': 'object',
        'currency_unit_name': 'object',
        'current_power': 'object',
        'customer': 'object',
        'customer_name': 'object',
        'down_price': 'list[ChargingStationPriceBand]',
        'energy_storages': 'object',
        'grid_tied_type': 'object',
        'id': 'object',
        'image': 'object',
        'image_url': 'object',
        'is_shown': 'object',
        'latitude': 'object',
        'longitude': 'object',
        'name': 'object',
        'no': 'object',
        'old_agent': 'object',
        'org_code': 'object',
        'product_series': 'object',
        'product_series_name': 'object',
        'pv_arrange': 'object',
        'pv_capacity': 'object',
        'pv_capacity_unit': 'object',
        'pv_type': 'object',
        'quarter_report': 'object',
        'quarter_report_email': 'object',
        'registration_time': 'object',
        'registration_time_zone': 'object',
        'series': 'object',
        'status': 'object',
        'system_efficiency': 'object',
        'system_type': 'object',
        'system_type_name': 'object',
        'timezone': 'object',
        'timezone_name': 'object',
        'timezone_value': 'object',
        'today_power_generation': 'object',
        'total_capacity': 'object',
        'total_power_generation': 'object',
        'up_price': 'list[ChargingStationPriceBand]',
        'update_time': 'object',
        'update_time_zone': 'object',
        'work_status': 'object'
    }

    attribute_map = {
        'adress': 'adress',
        'agent': 'agent',
        'agent_and_parent': 'agentAndParent',
        'battery_capacity': 'batteryCapacity',
        'battery_capacity_unit': 'batteryCapacityUnit',
        'charging_capacity': 'chargingCapacity',
        'charging_type': 'chargingType',
        'charging_type_name': 'chargingTypeName',
        'code_name': 'codeName',
        'country': 'country',
        'country_name': 'countryName',
        'country_value': 'countryValue',
        'create_source': 'createSource',
        'creator_id': 'creatorId',
        'creator_type': 'creatorType',
        'currency_symbol': 'currencySymbol',
        'currency_unit': 'currencyUnit',
        'currency_unit_name': 'currencyUnitName',
        'current_power': 'currentPower',
        'customer': 'customer',
        'customer_name': 'customerName',
        'down_price': 'downPrice',
        'energy_storages': 'energyStorages',
        'grid_tied_type': 'gridTiedType',
        'id': 'id',
        'image': 'image',
        'image_url': 'imageUrl',
        'is_shown': 'isShown',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'name': 'name',
        'no': 'no',
        'old_agent': 'oldAgent',
        'org_code': 'orgCode',
        'product_series': 'productSeries',
        'product_series_name': 'productSeriesName',
        'pv_arrange': 'pvArrange',
        'pv_capacity': 'pvCapacity',
        'pv_capacity_unit': 'pvCapacityUnit',
        'pv_type': 'pvType',
        'quarter_report': 'quarterReport',
        'quarter_report_email': 'quarterReportEmail',
        'registration_time': 'registrationTime',
        'registration_time_zone': 'registrationTimeZone',
        'series': 'series',
        'status': 'status',
        'system_efficiency': 'systemEfficiency',
        'system_type': 'systemType',
        'system_type_name': 'systemTypeName',
        'timezone': 'timezone',
        'timezone_name': 'timezoneName',
        'timezone_value': 'timezoneValue',
        'today_power_generation': 'todayPowerGeneration',
        'total_capacity': 'totalCapacity',
        'total_power_generation': 'totalPowerGeneration',
        'up_price': 'upPrice',
        'update_time': 'updateTime',
        'update_time_zone': 'updateTimeZone',
        'work_status': 'workStatus'
    }

    def __init__(self, adress=None, agent=None, agent_and_parent=None, battery_capacity=None, battery_capacity_unit=None, charging_capacity=None, charging_type=None, charging_type_name=None, code_name=None, country=None, country_name=None, country_value=None, create_source=None, creator_id=None, creator_type=None, currency_symbol=None, currency_unit=None, currency_unit_name=None, current_power=None, customer=None, customer_name=None, down_price=None, energy_storages=None, grid_tied_type=None, id=None, image=None, image_url=None, is_shown=None, latitude=None, longitude=None, name=None, no=None, old_agent=None, org_code=None, product_series=None, product_series_name=None, pv_arrange=None, pv_capacity=None, pv_capacity_unit=None, pv_type=None, quarter_report=None, quarter_report_email=None, registration_time=None, registration_time_zone=None, series=None, status=None, system_efficiency=None, system_type=None, system_type_name=None, timezone=None, timezone_name=None, timezone_value=None, today_power_generation=None, total_capacity=None, total_power_generation=None, up_price=None, update_time=None, update_time_zone=None, work_status=None):  # noqa: E501,A002
        self._adress = None
        self._agent = None
        self._agent_and_parent = None
        self._battery_capacity = None
        self._battery_capacity_unit = None
        self._charging_capacity = None
        self._charging_type = None
        self._charging_type_name = None
        self._code_name = None
        self._country = None
        self._country_name = None
        self._country_value = None
        self._create_source = None
        self._creator_id = None
        self._creator_type = None
        self._currency_symbol = None
        self._currency_unit = None
        self._currency_unit_name = None
        self._current_power = None
        self._customer = None
        self._customer_name = None
        self._down_price = None
        self._energy_storages = None
        self._grid_tied_type = None
        self._id = None
        self._image = None
        self._image_url = None
        self._is_shown = None
        self._latitude = None
        self._longitude = None
        self._name = None
        self._no = None
        self._old_agent = None
        self._org_code = None
        self._product_series = None
        self._product_series_name = None
        self._pv_arrange = None
        self._pv_capacity = None
        self._pv_capacity_unit = None
        self._pv_type = None
        self._quarter_report = None
        self._quarter_report_email = None
        self._registration_time = None
        self._registration_time_zone = None
        self._series = None
        self._status = None
        self._system_efficiency = None
        self._system_type = None
        self._system_type_name = None
        self._timezone = None
        self._timezone_name = None
        self._timezone_value = None
        self._today_power_generation = None
        self._total_capacity = None
        self._total_power_generation = None
        self._up_price = None
        self._update_time = None
        self._update_time_zone = None
        self._work_status = None
        self.discriminator = None
        if adress is not None:
            self.adress = adress
        if agent is not None:
            self.agent = agent
        if agent_and_parent is not None:
            self.agent_and_parent = agent_and_parent
        if battery_capacity is not None:
            self.battery_capacity = battery_capacity
        if battery_capacity_unit is not None:
            self.battery_capacity_unit = battery_capacity_unit
        if charging_capacity is not None:
            self.charging_capacity = charging_capacity
        if charging_type is not None:
            self.charging_type = charging_type
        if charging_type_name is not None:
            self.charging_type_name = charging_type_name
        if code_name is not None:
            self.code_name = code_name
        if country is not None:
            self.country = country
        if country_name is not None:
            self.country_name = country_name
        if country_value is not None:
            self.country_value = country_value
        if create_source is not None:
            self.create_source = create_source
        if creator_id is not None:
            self.creator_id = creator_id
        if creator_type is not None:
            self.creator_type = creator_type
        if currency_symbol is not None:
            self.currency_symbol = currency_symbol
        if currency_unit is not None:
            self.currency_unit = currency_unit
        if currency_unit_name is not None:
            self.currency_unit_name = currency_unit_name
        if current_power is not None:
            self.current_power = current_power
        if customer is not None:
            self.customer = customer
        if customer_name is not None:
            self.customer_name = customer_name
        if down_price is not None:
            self.down_price = down_price
        if energy_storages is not None:
            self.energy_storages = energy_storages
        if grid_tied_type is not None:
            self.grid_tied_type = grid_tied_type
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if image_url is not None:
            self.image_url = image_url
        if is_shown is not None:
            self.is_shown = is_shown
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if name is not None:
            self.name = name
        if no is not None:
            self.no = no
        if old_agent is not None:
            self.old_agent = old_agent
        if org_code is not None:
            self.org_code = org_code
        if product_series is not None:
            self.product_series = product_series
        if product_series_name is not None:
            self.product_series_name = product_series_name
        if pv_arrange is not None:
            self.pv_arrange = pv_arrange
        if pv_capacity is not None:
            self.pv_capacity = pv_capacity
        if pv_capacity_unit is not None:
            self.pv_capacity_unit = pv_capacity_unit
        if pv_type is not None:
            self.pv_type = pv_type
        if quarter_report is not None:
            self.quarter_report = quarter_report
        if quarter_report_email is not None:
            self.quarter_report_email = quarter_report_email
        if registration_time is not None:
            self.registration_time = registration_time
        if registration_time_zone is not None:
            self.registration_time_zone = registration_time_zone
        if series is not None:
            self.series = series
        if status is not None:
            self.status = status
        if system_efficiency is not None:
            self.system_efficiency = system_efficiency
        if system_type is not None:
            self.system_type = system_type
        if system_type_name is not None:
            self.system_type_name = system_type_name
        if timezone is not None:
            self.timezone = timezone
        if timezone_name is not None:
            self.timezone_name = timezone_name
        if timezone_value is not None:
            self.timezone_value = timezone_value
        if today_power_generation is not None:
            self.today_power_generation = today_power_generation
        if total_capacity is not None:
            self.total_capacity = total_capacity
        if total_power_generation is not None:
            self.total_power_generation = total_power_generation
        if up_price is not None:
            self.up_price = up_price
        if update_time is not None:
            self.update_time = update_time
        if update_time_zone is not None:
            self.update_time_zone = update_time_zone
        if work_status is not None:
            self.work_status = work_status

    @property
    def adress(self):
        return self._adress

    @adress.setter
    def adress(self, adress):
        self._adress = adress

    @property
    def agent(self):
        return self._agent

    @agent.setter
    def agent(self, agent):
        self._agent = agent

    @property
    def agent_and_parent(self):
        return self._agent_and_parent

    @agent_and_parent.setter
    def agent_and_parent(self, agent_and_parent):
        self._agent_and_parent = agent_and_parent

    @property
    def battery_capacity(self):
        return self._battery_capacity

    @battery_capacity.setter
    def battery_capacity(self, battery_capacity):
        self._battery_capacity = battery_capacity

    @property
    def battery_capacity_unit(self):
        return self._battery_capacity_unit

    @battery_capacity_unit.setter
    def battery_capacity_unit(self, battery_capacity_unit):
        self._battery_capacity_unit = battery_capacity_unit

    @property
    def charging_capacity(self):
        return self._charging_capacity

    @charging_capacity.setter
    def charging_capacity(self, charging_capacity):
        self._charging_capacity = charging_capacity

    @property
    def charging_type(self):
        return self._charging_type

    @charging_type.setter
    def charging_type(self, charging_type):
        self._charging_type = charging_type

    @property
    def charging_type_name(self):
        return self._charging_type_name

    @charging_type_name.setter
    def charging_type_name(self, charging_type_name):
        self._charging_type_name = charging_type_name

    @property
    def code_name(self):
        return self._code_name

    @code_name.setter
    def code_name(self, code_name):
        self._code_name = code_name

    @property
    def country(self):
        return self._country

    @country.setter
    def country(self, country):
        self._country = country

    @property
    def country_name(self):
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        self._country_name = country_name

    @property
    def country_value(self):
        return self._country_value

    @country_value.setter
    def country_value(self, country_value):
        self._country_value = country_value

    @property
    def create_source(self):
        return self._create_source

    @create_source.setter
    def create_source(self, create_source):
        self._create_source = create_source

    @property
    def creator_id(self):
        return self._creator_id

    @creator_id.setter
    def creator_id(self, creator_id):
        self._creator_id = creator_id

    @property
    def creator_type(self):
        return self._creator_type

    @creator_type.setter
    def creator_type(self, creator_type):
        self._creator_type = creator_type

    @property
    def currency_symbol(self):
        return self._currency_symbol

    @currency_symbol.setter
    def currency_symbol(self, currency_symbol):
        self._currency_symbol = currency_symbol

    @property
    def currency_unit(self):
        return self._currency_unit

    @currency_unit.setter
    def currency_unit(self, currency_unit):
        self._currency_unit = currency_unit

    @property
    def currency_unit_name(self):
        return self._currency_unit_name

    @currency_unit_name.setter
    def currency_unit_name(self, currency_unit_name):
        self._currency_unit_name = currency_unit_name

    @property
    def current_power(self):
        return self._current_power

    @current_power.setter
    def current_power(self, current_power):
        self._current_power = current_power

    @property
    def customer(self):
        return self._customer

    @customer.setter
    def customer(self, customer):
        self._customer = customer

    @property
    def customer_name(self):
        return self._customer_name

    @customer_name.setter
    def customer_name(self, customer_name):
        self._customer_name = customer_name

    @property
    def down_price(self):
        return self._down_price

    @down_price.setter
    def down_price(self, down_price):
        self._down_price = down_price

    @property
    def energy_storages(self):
        return self._energy_storages

    @energy_storages.setter
    def energy_storages(self, energy_storages):
        self._energy_storages = energy_storages

    @property
    def grid_tied_type(self):
        return self._grid_tied_type

    @grid_tied_type.setter
    def grid_tied_type(self, grid_tied_type):
        self._grid_tied_type = grid_tied_type

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, id):  # noqa: A002
        self._id = id

    @property
    def image(self):
        return self._image

    @image.setter
    def image(self, image):
        self._image = image

    @property
    def image_url(self):
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        self._image_url = image_url

    @property
    def is_shown(self):
        return self._is_shown

    @is_shown.setter
    def is_shown(self, is_shown):
        self._is_shown = is_shown

    @property
    def latitude(self):
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        self._latitude = latitude

    @property
    def longitude(self):
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        self._longitude = longitude

    @property
    def name(self):
        return self._name

    @name.setter
    def name(self, name):
        self._name = name

    @property
    def no(self):
        return self._no

    @no.setter
    def no(self, no):
        self._no = no

    @property
    def old_agent(self):
        return self._old_agent

    @old_agent.setter
    def old_agent(self, old_agent):
        self._old_agent = old_agent

    @property
    def org_code(self):
        return self._org_code

    @org_code.setter
    def org_code(self, org_code):
        self._org_code = org_code

    @property
    def product_series(self):
        return self._product_series

    @product_series.setter
    def product_series(self, product_series):
        self._product_series = product_series

    @property
    def product_series_name(self):
        return self._product_series_name

    @product_series_name.setter
    def product_series_name(self, product_series_name):
        self._product_series_name = product_series_name

    @property
    def pv_arrange(self):
        return self._pv_arrange

    @pv_arrange.setter
    def pv_arrange(self, pv_arrange):
        self._pv_arrange = pv_arrange

    @property
    def pv_capacity(self):
        return self._pv_capacity

    @pv_capacity.setter
    def pv_capacity(self, pv_capacity):
        self._pv_capacity = pv_capacity

    @property
    def pv_capacity_unit(self):
        return self._pv_capacity_unit

    @pv_capacity_unit.setter
    def pv_capacity_unit(self, pv_capacity_unit):
        self._pv_capacity_unit = pv_capacity_unit

    @property
    def pv_type(self):
        return self._pv_type

    @pv_type.setter
    def pv_type(self, pv_type):
        self._pv_type = pv_type

    @property
    def quarter_report(self):
        return self._quarter_report

    @quarter_report.setter
    def quarter_report(self, quarter_report):
        self._quarter_report = quarter_report

    @property
    def quarter_report_email(self):
        return self._quarter_report_email

    @quarter_report_email.setter
    def quarter_report_email(self, quarter_report_email):
        self._quarter_report_email = quarter_report_email

    @property
    def registration_time(self):
        return self._registration_time

    @registration_time.setter
    def registration_time(self, registration_time):
        self._registration_time = registration_time

    @property
    def registration_time_zone(self):
        return self._registration_time_zone

    @registration_time_zone.setter
    def registration_time_zone(self, registration_time_zone):
        self._registration_time_zone = registration_time_zone

    @property
    def series(self):
        return self._series

    @series.setter
    def series(self, series):
        self._series = series

    @property
    def status(self):
        return self._status

    @status.setter
    def status(self, status):
        self._status = status

    @property
    def system_efficiency(self):
        return self._system_efficiency

    @system_efficiency.setter
    def system_efficiency(self, system_efficiency):
        self._system_efficiency = system_efficiency

    @property
    def system_type(self):
        return self._system_type

    @system_type.setter
    def system_type(self, system_type):
        self._system_type = system_type

    @property
    def system_type_name(self):
        return self._system_type_name

    @system_type_name.setter
    def system_type_name(self, system_type_name):
        self._system_type_name = system_type_name

    @property
    def timezone(self):
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        self._timezone = timezone

    @property
    def timezone_name(self):
        return self._timezone_name

    @timezone_name.setter
    def timezone_name(self, timezone_name):
        self._timezone_name = timezone_name

    @property
    def timezone_value(self):
        return self._timezone_value

    @timezone_value.setter
    def timezone_value(self, timezone_value):
        self._timezone_value = timezone_value

    @property
    def today_power_generation(self):
        return self._today_power_generation

    @today_power_generation.setter
    def today_power_generation(self, today_power_generation):
        self._today_power_generation = today_power_generation

    @property
    def total_capacity(self):
        return self._total_capacity

    @total_capacity.setter
    def total_capacity(self, total_capacity):
        self._total_capacity = total_capacity

    @property
    def total_power_generation(self):
        return self._total_power_generation

    @total_power_generation.setter
    def total_power_generation(self, total_power_generation):
        self._total_power_generation = total_power_generation

    @property
    def up_price(self):
        return self._up_price

    @up_price.setter
    def up_price(self, up_price):
        self._up_price = up_price

    @property
    def update_time(self):
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        self._update_time = update_time

    @property
    def update_time_zone(self):
        return self._update_time_zone

    @update_time_zone.setter
    def update_time_zone(self, update_time_zone):
        self._update_time_zone = update_time_zone

    @property
    def work_status(self):
        return self._work_status

    @work_status.setter
    def work_status(self, work_status):
        self._work_status = work_status

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChargingStation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, ChargingStation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
