# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ChargingStationPriceBand(object):
    """Tariff band attached to a charging-station record."""

    swagger_types = {
        'power_station': 'object',
        'price': 'object',
        'start_time': 'object',
        'end_time': 'object',
        'id': 'object'
    }

    attribute_map = {
        'power_station': 'powerStation',
        'price': 'price',
        'start_time': 'startTime',
        'end_time': 'endTime',
        'id': 'id'
    }

    def __init__(self, power_station=None, price=None, start_time=None, end_time=None, id=None):  # noqa: E501,A002
        self._power_station = None
        self._price = None
        self._start_time = None
        self._end_time = None
        self._id = None
        self.discriminator = None
        if power_station is not None:
            self.power_station = power_station
        if price is not None:
            self.price = price
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if id is not None:
            self.id = id

    @property
    def power_station(self):
        return self._power_station

    @power_station.setter
    def power_station(self, power_station):
        self._power_station = power_station

    @property
    def price(self):
        return self._price

    @price.setter
    def price(self, price):
        self._price = price

    @property
    def start_time(self):
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        self._start_time = start_time

    @property
    def end_time(self):
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        self._end_time = end_time

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, id):  # noqa: A002
        self._id = id

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChargingStationPriceBand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, ChargingStationPriceBand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
