# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DeviceListData(object):
    """Pagination payload for device list responses."""

    swagger_types = {
        'count': 'object',
        'list': 'DeviceList'
    }

    attribute_map = {
        'count': 'count',
        'list': 'list'
    }

    def __init__(self, count=None, list=None):  # noqa: E501,A002
        self._count = None
        self._list = None
        self.discriminator = None
        if count is not None:
            self.count = count
        if list is not None:
            self.list = list

    @property
    def count(self):
        return self._count

    @count.setter
    def count(self, count):
        self._count = count

    @property
    def list(self):
        return self._list

    @list.setter
    def list(self, list):  # noqa: A002
        self._list = list

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceListData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, DeviceListData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
