# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DeviceEnergySummary(object):
    """Lifetime generation or consumption for a device."""

    swagger_types = {
        'pv_produce_electric': 'object',
        'load_customer_electric': 'object',
        'timestamp': 'object'
    }

    attribute_map = {
        'pv_produce_electric': 'pvProduceElectric',
        'load_customer_electric': 'loadCustomerElectric',
        'timestamp': 'timestamp'
    }

    def __init__(self, pv_produce_electric=None, load_customer_electric=None, timestamp=None):  # noqa: E501
        self._pv_produce_electric = None
        self._load_customer_electric = None
        self._timestamp = None
        self.discriminator = None
        if pv_produce_electric is not None:
            self.pv_produce_electric = pv_produce_electric
        if load_customer_electric is not None:
            self.load_customer_electric = load_customer_electric
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def pv_produce_electric(self):
        return self._pv_produce_electric

    @pv_produce_electric.setter
    def pv_produce_electric(self, pv_produce_electric):
        self._pv_produce_electric = pv_produce_electric

    @property
    def load_customer_electric(self):
        return self._load_customer_electric

    @load_customer_electric.setter
    def load_customer_electric(self, load_customer_electric):
        self._load_customer_electric = load_customer_electric

    @property
    def timestamp(self):
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        self._timestamp = timestamp

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceEnergySummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, DeviceEnergySummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
