# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class EnergyStorageController(object):
    """Compatibility model retained for existing generated tests."""

    swagger_types = {
        'alarm_status': 'object',
        'battery_info': 'object',
        'battery_info_unit': 'object',
        'battery_power': 'object',
        'battery_power_unit': 'object',
        'battery_soc': 'object',
        'battery_type': 'object',
        'battery_voltage': 'object',
        'battery_voltage_unit': 'object',
        'capacity': 'object',
        'capacity_unit': 'object',
        'carbon_reduction': 'object',
        'carbon_reduction_unit': 'object',
        'collector_sn': 'object',
        'currency_symbol': 'object',
        'e_total_to_grid_unit': 'object',
        'eout_daily_unit': 'object',
        'grid_active_power': 'object',
        'grid_active_power_unit': 'object',
        'input_frequency': 'object',
        'input_frequency_unit': 'object',
        'input_voltage': 'object',
        'input_voltage_unit': 'object',
        'intensity': 'object',
        'inverter_sn': 'object',
        'load_power': 'object',
        'load_power_unit': 'object',
        'name': 'object',
        'power_station_id': 'object',
        'power_station_name': 'object',
        'product_type_name': 'object',
        'pv_info': 'object',
        'pv_info_unit': 'object',
        'pv_power': 'object',
        'pv_power_unit': 'object',
        'registration_time': 'object',
        'registration_time_zone': 'object',
        'status': 'object',
        'temperature': 'object',
        'today_power_generation': 'object',
        'today_profit': 'object',
        'total_power_generation': 'object',
        'total_profit': 'object',
        'update_time': 'object',
        'update_time_zone': 'object',
        'work_status': 'object'
    }

    attribute_map = {
        'alarm_status': 'alarmStatus',
        'battery_info': 'batteryInfo',
        'battery_info_unit': 'batteryInfoUnit',
        'battery_power': 'batteryPower',
        'battery_power_unit': 'batteryPowerUnit',
        'battery_soc': 'batterySoc',
        'battery_type': 'batteryType',
        'battery_voltage': 'batteryVoltage',
        'battery_voltage_unit': 'batteryVoltageUnit',
        'capacity': 'capacity',
        'capacity_unit': 'capacityUnit',
        'carbon_reduction': 'carbonReduction',
        'carbon_reduction_unit': 'carbonReductionUnit',
        'collector_sn': 'collectorSn',
        'currency_symbol': 'currencySymbol',
        'e_total_to_grid_unit': 'eTotalToGridUnit',
        'eout_daily_unit': 'eoutDailyUnit',
        'grid_active_power': 'gridActivePower',
        'grid_active_power_unit': 'gridActivePowerUnit',
        'input_frequency': 'inputFrequency',
        'input_frequency_unit': 'inputFrequencyUnit',
        'input_voltage': 'inputVoltage',
        'input_voltage_unit': 'inputVoltageUnit',
        'intensity': 'intensity',
        'inverter_sn': 'inverterSn',
        'load_power': 'loadPower',
        'load_power_unit': 'loadPowerUnit',
        'name': 'name',
        'power_station_id': 'powerStationId',
        'power_station_name': 'powerStationName',
        'product_type_name': 'productTypeName',
        'pv_info': 'pvInfo',
        'pv_info_unit': 'pvInfoUnit',
        'pv_power': 'pvPower',
        'pv_power_unit': 'pvPowerUnit',
        'registration_time': 'registrationTime',
        'registration_time_zone': 'registrationTimeZone',
        'status': 'status',
        'temperature': 'temperature',
        'today_power_generation': 'todayPowerGeneration',
        'today_profit': 'todayProfit',
        'total_power_generation': 'totalPowerGeneration',
        'total_profit': 'totalProfit',
        'update_time': 'updateTime',
        'update_time_zone': 'updateTimeZone',
        'work_status': 'workStatus'
    }

    def __init__(self, **kwargs):
        self.discriminator = None
        for attr in self.swagger_types:
            setattr(self, '_' + attr, None)
            if attr in kwargs and kwargs[attr] is not None:
                setattr(self, attr, kwargs[attr])

    def __getattr__(self, item):
        private_name = '_' + item
        if private_name in self.__dict__:
            return self.__dict__[private_name]
        raise AttributeError(item)

    def __setattr__(self, key, value):
        if key in getattr(self, 'swagger_types', {}):
            super(EnergyStorageController, self).__setattr__('_' + key, value)
        else:
            super(EnergyStorageController, self).__setattr__(key, value)

    def to_dict(self):
        result = {}
        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, 'to_dict') else x for x in value]
            elif hasattr(value, 'to_dict'):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    (k, v.to_dict() if hasattr(v, 'to_dict') else v)
                    for k, v in value.items()
                )
            else:
                result[attr] = value
        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        return isinstance(other, EnergyStorageController) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
