# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EnergyStorageController(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sn': 'object',
        'model_type': 'object'
    }

    attribute_map = {
        'sn': 'sn',
        'model_type': 'modelType'
    }

    def __init__(self, sn=None, model_type=None):  # noqa: E501
        """EnergyStorageController - a model defined in Swagger"""  # noqa: E501
        self._sn = None
        self._model_type = None
        self.discriminator = None
        if sn is not None:
            self.sn = sn
        if model_type is not None:
            self.model_type = model_type

    @property
    def sn(self):
        """Gets the sn of this EnergyStorageController.  # noqa: E501

        Serial Number  # noqa: E501

        :return: The sn of this EnergyStorageController.  # noqa: E501
        :rtype: object
        """
        return self._sn

    @sn.setter
    def sn(self, sn):
        """Sets the sn of this EnergyStorageController.

        Serial Number  # noqa: E501

        :param sn: The sn of this EnergyStorageController.  # noqa: E501
        :type: object
        """

        self._sn = sn

    @property
    def model_type(self):
        """Gets the model_type of this EnergyStorageController.  # noqa: E501

        Model Type  # noqa: E501

        :return: The model_type of this EnergyStorageController.  # noqa: E501
        :rtype: object
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this EnergyStorageController.

        Model Type  # noqa: E501

        :param model_type: The model_type of this EnergyStorageController.  # noqa: E501
        :type: object
        """

        self._model_type = model_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnergyStorageController, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnergyStorageController):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
