# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LoginResponseData(object):
    """Represents the nested payload returned by the login endpoint."""

    swagger_types = {
        'msg_code': 'object',
        'message': 'object',
        'data': 'object',
        'msg_code_legacy': 'object'
    }

    attribute_map = {
        'msg_code': 'msgCode',
        'message': 'message',
        'data': 'data',
        'msg_code_legacy': 'msg_code'
    }

    def __init__(self, msg_code=None, message=None, data=None, msg_code_legacy=None):  # noqa: E501
        self._msg_code = None
        self._message = None
        self._data = None
        self._msg_code_legacy = None
        self.discriminator = None
        if msg_code is not None:
            self.msg_code = msg_code
        if message is not None:
            self.message = message
        if data is not None:
            self.data = data
        if msg_code_legacy is not None:
            self.msg_code_legacy = msg_code_legacy

    @property
    def msg_code(self):
        return self._msg_code

    @msg_code.setter
    def msg_code(self, msg_code):
        self._msg_code = msg_code

    @property
    def message(self):
        return self._message

    @message.setter
    def message(self, message):
        self._message = message

    @property
    def data(self):
        return self._data

    @data.setter
    def data(self, data):
        self._data = data

    @property
    def msg_code_legacy(self):
        return self._msg_code_legacy

    @msg_code_legacy.setter
    def msg_code_legacy(self, msg_code_legacy):
        self._msg_code_legacy = msg_code_legacy

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoginResponseData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, LoginResponseData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
