# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RecentGridImportExport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    swagger_types = {
        'site_id': 'object',
        'ts': 'object',
        'positive': 'object',
        'negative': 'object'
    }

    attribute_map = {
        'site_id': 'siteId',
        'ts': 'ts',
        'positive': 'positive',
        'negative': 'negative'
    }

    def __init__(self, site_id=None, ts=None, positive=None, negative=None):  # noqa: E501
        self._site_id = None
        self._ts = None
        self._positive = None
        self._negative = None
        self.discriminator = None
        if site_id is not None:
            self.site_id = site_id
        if ts is not None:
            self.ts = ts
        if positive is not None:
            self.positive = positive
        if negative is not None:
            self.negative = negative

    @property
    def site_id(self):
        return self._site_id

    @site_id.setter
    def site_id(self, site_id):
        self._site_id = site_id

    @property
    def ts(self):
        return self._ts

    @ts.setter
    def ts(self, ts):
        self._ts = ts

    @property
    def positive(self):
        return self._positive

    @positive.setter
    def positive(self, positive):
        self._positive = positive

    @property
    def negative(self):
        return self._negative

    @negative.setter
    def negative(self, negative):
        self._negative = negative

    def to_dict(self):
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecentGridImportExport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, RecentGridImportExport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
