name: Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Git Version
      uses: codacy/git-version@2.4.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build bump2version
    - id: get-latest-tag
      uses: actions-ecosystem/action-get-latest-tag@v1
    - id: extract-version
      run: |
        version=$(echo ${{steps.get-latest-tag.outputs.tag}} | cut -b2-)
        echo "version=$version" >> $GITHUB_OUTPUT
    - name: File Regex Replace
      uses: mingjun97/file-regex-replace@v1
      with:
        regex: "VERSION = \"(\\d*\\.\\d*\\.\\d*)\""
        replacement: "VERSION = \"${{ steps.extract-version.outputs.version }}\""
        include: setup.py
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
